
/* CRIA A TABELA DEPARTAMENTO */
CREATE TABLE DEPARTAMENTO
(
	ID_DEPTO INT PRIMARY KEY,
	DESCRICAO VARCHAR2(50) NOT NULL
);

/* INSERE DADOS NA TABELA DEPARTAMENTO */
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (1, 'FÁBRICA DE SOFTWARE');
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (2, 'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO (ID_DEPTO, DESCRICAO) VALUES (3, 'FINANCEIRO');

/* CRIA A TABELA FUNCIONARIO */
CREATE TABLE FUNCIONARIO
(
	ID_FUNC INT PRIMARY KEY,
	NOME VARCHAR2(50) NOT NULL,
	DATA_NASC DATE NOT NULL,
	GENERO CHAR(1),
	ENDERECO VARCHAR2(70) NOT NULL,
	BAIRRO VARCHAR2(30) NOT NULL,
	CIDADE VARCHAR2(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
    ID_DEPTO INT,
	CONSTRAINT CK_GENERO CHECK (GENERO='F' OR GENERO='M'),
	CONSTRAINT FK_DEPTO FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO (ID_DEPTO)
);


--Criando a Sequence FUNC_SEQ
CREATE SEQUENCE FUNC_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

/* INSERE DADOS NA TABELA FUNCIONARIO */

INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'ANA MARIA LOPES CANDIDO', '25/05/1980', 'F','R. DA PRATA', 'JD BELEM', 'BARUERI', 'SP', 6000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'ROBERTO PEREIRA DIAS','02/04/1975','M','R. DAS PALMEIRAS', 'JD. SANTA CLARA', 'SÃO PAULO', 'SP', 10000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'CELIA REGINA AVARENGA','02/11/1975','F','R. DAS ROSAS', 'PARAÍSO', 'SÃO PAULO', 'SP', 8000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'LETICIA PATRICIA ARAUJO','02/04/1975','F','R. TERCEIRO', 'JD. TUPÃ', 'BARUERI', 'SP', 6000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'JOAO BATISTA MORGADO','05/04/1975','M','R. RUBIA', 'JD. SANTA CLARA', 'OSASCO', 'SP', 5000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'CARLOS ANTONIO COSTA','02/12/1975','M','R. DR. ANTONIO', 'JD. SANTA CLARA', 'OSASCO', 'SP', 5000, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'JOSE VAGNER CESAR DE FREITAS','24/12/1984','M','R. DAS ANDORINHAS', 'JD. OUTONO', 'JANDIRA', 'SP', 1500, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'ANTONIA DOS SANTOS','14/12/1984','F','R. DIAMANTES', 'JD. PRIMAVERA', 'OSASCO', 'SP', 5500, 1);
INSERT INTO FUNCIONARIO (ID_FUNC, NOME, DATA_NASC, GENERO, ENDERECO, BAIRRO, CIDADE, ESTADO, SALARIO, ID_DEPTO) VALUES (FUNC_SEQ.NEXTVAL, 'BEATRIZ SOUZA', '02/03/1984','F','R. DAS ANDORINHAS', 'JD. OUTONO', 'BARUERI', 'SP', 7500, 1);

/* CRIA A TABELA PROJETO */
CREATE TABLE PROJETO
(
	ID_PROJ INT PRIMARY KEY,
	NOME VARCHAR2(50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NULL,
	ID_GESTOR INT,
    CONSTRAINT FK_GESTOR FOREIGN KEY (ID_GESTOR) REFERENCES FUNCIONARIO (ID_FUNC)
);

INSERT INTO PROJETO VALUES (1, 'REESTRUTURAÇÃO DE NOTA FISCAL ELETRÔNICA', '20/02/2009', '20/02/2010', 2);
INSERT INTO PROJETO VALUES (2, 'PROJETO DE MELHORIAS CONTÍNUAS', '01/02/2009', '02/05/2012', 3);

 /* CRIA A TABELA PROJETO X FUNCIONARIO*/
CREATE TABLE PROJ_FUNC
(
	ID_PROJ INT, 
	ID_FUNC INT, 
	CONSTRAINT PK_PROJ_FUNC PRIMARY KEY (ID_PROJ, ID_FUNC),
	CONSTRAINT FK_PROJETO FOREIGN KEY (ID_PROJ) REFERENCES PROJETO (ID_PROJ),
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (ID_FUNC) REFERENCES FUNCIONARIO (ID_FUNC)
);

INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 1);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 5);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 6);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 7);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (1, 8);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 9);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 5);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 6);
INSERT INTO PROJ_FUNC (ID_PROJ, ID_FUNC) VALUES (2, 7);

--=========================================================================

--Q1
CREATE TABLE  ID_CARGO
( 
ID_CARGO INT,
DESCRICAO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_ID_CARGO PRIMARY KEY (ID_CARGO),
CONSTRAINT FK_DEPTO FOREIGN KEY (DESCRICAO) REFERENCES DEPARTAMENTO (DESCRICAO)
);

--Q2
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT ID_CARGO UNIQUE (ID_CARGO);

--Q3
INSERT INTO ID_CARGO (ID_CARGO, DESCRICAO) VALUES (1, 'Gerentes de Projeto');
INSERT INTO ID_CARGO (ID_CARGO, DESCRICAO) VALUES (2, 'Analista de Sistemas');
INSERT INTO ID_CARGO (ID_CARGO, DESCRICAO) VALUES (3, 'Desenvolvedor');
INSERT INTO ID_CARGO (ID_CARGO, DESCRICAO) VALUES (4, 'Analistas de Teste');

--Q4
UPDATE FUNCIONARIO SET SÃO PAULO = 'Gerente de Projetos';

UPDATE FUNCIONARIO SET BARUERI = 'Analista de Sistemas';

UPDATE FUNCIONARIO SET BARUERI = 'Desenvolvedor';

UPDATE FUNCIONARIO SET JANDIRA = 'Analistas de Testes';
 
--Q7
 SELECT FUNCIONARIO.NOME, ID_CARGO.DESCRICAO
FROM FUNCIONARIO INNER JOIN ID_CARGO
ON FUNCIONARIO.ID_FUNC = ID_CARGO.DESCRICAO


SELECT NOME, COUNT (NOME) AS NOME FROM FUNCIONARIO 
GROUP BY NOME;


