SELECT LIVRO.TITULO, CATEGORIA.DESCRICAO, LIVRO.PRECO
FROM LIVRO RIGHT JOIN CATEGORIA 
ON LIVRO.COD_CATEGORIA = CATEGORIA.COD_CATEGORIA;

SELECT CLIENTE.NOME, PEDIDO.VALOR_TOTAL, 
PEDIDO.COD_PEDIDO, PEDIDO.DATA_PEDIDO
FROM PEDIDO INNER JOIN CLIENTE
ON CLIENTE.COD_CLIENTE = PEDIDO.COD_CLIENTE;

SELECT LIVRO.TITULO FROM LIVRO INNER JOIN ITEM_PEDIDO
ON LIVRO.COD_LIVRO = ITEM_PEDIDO.COD_LIVRO

SELECT LIVRO.TITULO, COUNT(LIVRO.TITULO) AS QTDE 
FROM LIVRO INNER JOIN ITEM_PEDIDO
ON LIVRO.COD_LIVRO = ITEM_PEDIDO.COD_LIVRO
GROUP BY LIVRO.TITULO;

SELECT LIVRO.TITULO, CATEGORIA.DESCRICAO, LIVRO.PRECO,
AUTOR.NOME FROM LIVRO 
INNER JOIN CATEGORIA 
ON LIVRO.COD_CATEGORIA = CATEGORIA.COD_CATEGORIA
INNER JOIN LIVRO_AUTOR 
ON LIVRO.COD_LIVRO = LIVRO_AUTOR.COD_LIVRO
INNER JOIN AUTOR
ON AUTOR.COD_AUTOR = LIVRO_AUTOR.COD_AUTOR;

select * from livro;