EXERCÍCIO:
--CRIE UMA VIEW QUE REALIZE UMA QUERY PARA
CONSULTAR Os NOMEs DOS CLIENTES, título
DO LIVRO,NÚMERO DO PEDIDO E A DATA DO 
PEDIDO QUE 
COMPRARAM qualquer livro 'Use a Cabeça!' 
****************************************
SELECT TITULO.LIVRO, AUTOR.NOME FROM
LIVRO INNER JOIN LIVRO_AUTOR
ON LIVRO.COD_LIVRO = LIVRO_AUTOR.COD_LIVRO
INNER JOIN AUTOR
ON LIVRO_AUTOR.COD_AUTOR = AUTOR.COD_AUTOR;