--EXCLUINDO A TABELA CATEGORIA
DROP TABLE CATEGORIA;

--CRIANDO A TABELA CATEGORIA
CREATE  TABLE CATEGORIA
(
COD_CATEGORIA INT,
DESCRICAO VARCHAR2(80) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
);

--CONSULTANDO A TABELA CATEGORIA
SELECT * FROM CATEGORIA;


--INSERINDO DADOS NA TABELA CATEGORIA
INSERT INTO CATEGORIA (COD_CATEGORIA, DESCRICAO) VALUES (1, 'INFORMÁTICA');
INSERT INTO CATEGORIA (COD_CATEGORIA, DESCRICAO) VALUES (2, 'DIDÁTICO');
INSERT INTO CATEGORIA (COD_CATEGORIA, DESCRICAO) VALUES (3, 'INFANTO-JUVENIL');
INSERT INTO CATEGORIA (COD_CATEGORIA, DESCRICAO) VALUES (4, 'INFANTIL');
INSERT INTO CATEGORIA (COD_CATEGORIA, DESCRICAO) VALUES (5, 'MEDICINA');


--
DROP TABLE LIVRO;

--CRIANDO A TABELA LIVRO,
CREATE TABLE LIVRO
(
COD_LIVRO INT,
TITULO VARCHAR2(80) NOT NULL,
ANO VARCHAR2(4) NOT NULL,
COD_CATEGORIA INT,
CONSTRAINT PK_LIVRO PRIMARY KEY (COD_LIVRO),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (COD_CATEGORIA)
);

SELECT * FROM LIVRO;

INSERT INTO LIVRO (COD_LIVRO, TITULO, ANO, COD_CATEGORIA) VALUES (1, 'HARRY POTTER', '2000', 3);
INSERT INTO LIVRO (COD_LIVRO, TITULO, ANO, COD_CATEGORIA) VALUES (2, 'VISÕES DE ROBO', '2000', 6);



