select
service_id, name, NETWORK_NAME, CREATION_DATE, blocked
select * from V$ACTIVE_SERVICES;

select NAME, CREATED, OPEN_MODE, VERSION_TIME, PLATFORM_NAME from V$DATABASE;

select * from V$SGA;

select * from V$SGAINFO;

select * from V$SGASTAT;

Create table CONFIRMACAO(
CAMPO1 VARCHAR(10) NOT NULL);

INSERT INTO CONFIRMACAO (CAMPO1) VALUES ('DADO x');

SELECT * FROM CONFIRMACAO;

ROLLBACK

SELECT * FROM CONFIRMACAO;

INSERT INTO CONFIRMACAO (CAMPO1) VALUES ('DADO x');

SELECT * FROM CONFIRMACAO;

COMMIT

SELECT * FROM CONFIRMACAO;

ROLLBACK;

SELECT * FROM CONFIRMACAO;





