--ATIVIDADE OLIMPIADA
--1- CRIAR UMA TABLESPACE CHAMADA OLIMPIADA, COM 5MB DE TAMANHO
--CRESCIMENTO AUTOMÁTICO E TAMANHO MÁXIMO DE 5MB.

CREATE TABLESPACE OLIMPIADA
DATAFILE 'D:\ORACLE\OLIMPIADA.DBF'
SIZE 5M AUTOEXTEND ON NEXT 20M
MAXSIZE 50M;

--2- CRIAR UM USUÁRIO CHAMADO atleta COM SENHA 1234, LIGADO À
--TABLESPACE OLIMPIADA

Create user atleta identified by 1234 default tablespace OLIMPIADA;

--3- FORNECER PERMISSÕES TOTAIS AO USUÁRIO atleta E SE CONECTAR COM ELE.

GRANT ALL PRIVILEGES TO atleta;

--4- Criar a tabela abaixo e realizar a inserção dos dados:
--DROP TABLE MODALIDADE
CREATE TABLE MODALIDADE(
CODIGO INT CONSTRAINT PK_MODALIDADE PRIMARY KEY,
NOME VARCHAR2(50) NOT NULL,
CATEGORIA VARCHAR2(30) NOT NULL,
DURACAO INT NULL,
LOCAL_DE_COMPETICAO VARCHAR2(50) NOT NULL,
PREMIACAO NUMERIC(10,2) NOT NULL) TABLESPACE OLIMPIADA;

--INSERÇÃO
INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(01, 'FUTEBOL', 'EQUIPE', 120,
'ARENA', 17000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(02, 'VOLEY', 'EQUIPE', 210,
'GINÁSIO', 13000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(03, 'ATLETISMO', 'INDIVIDUAL', null,
'ESTÁDIO', 35000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(04, 'ATLETISMO', 'EQUIPE', null,
'ESTÁDIO', 17000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(05, 'BOXE', 'INDIVIDUAL', 40,
'GINÁSIO', 17000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(06, 'JUDÔ', 'INDIVIDUAL', 10,
'GINÁSIO', 35000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(07, 'PÓLO AQUÁTICO', 'EQUIPE', 120,
'PISCINA', 17000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(08, 'BASQUETE', 'EQUIPE', 90,
'ARENA', 17000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(09, 'NATAÇÃO', 'INDIVIDUAL', null,
'PISCINA', 35000.00);

INSERT INTO MODALIDADE (CODIGO, NOME, CATEGORIA, DURACAO, 
LOCAL_DE_COMPETICAO, PREMIACAO)
VALUES
(10, 'NATAÇÃO', 'EQUIPE', null,
'PISCINA', 17000.00);

--CONSULTA GENÉRICA
SELECT CODIGO, NOME, CATEGORIA, DURACAO "Duração em minutos",
LOCAL_DE_COMPETICAO, PREMIACAO "Premiação" FROM MODALIDADE;

SELECT CODIGO, NOME, CATEGORIA, to_char(DURACAO) " Duração em minutos",
LOCAL_DE_COMPETICAO, TO_CHAR(PREMIACAO, '999,999.99')
FROM MODALIDADE;

--ATIVIDADE PESQUISA (OLIMPIADA):

--1- Retornar uma lista das modalidades ordenada pelo nome.
SELECT NOME "MODALIDADES"
FROM MODALIDADE
ORDER BY NOME ASC;

--2- Retornar uma lista das categorias existentes, sem repetição.
SELECT DISTINCT CATEGORIA "CATEGORIAS"
FROM MODALIDADE;

--3- Retornar a competição que demora mais para terminar.
SELECT NOME "MODALIDADE QUE MAIS DEMORA", DURACAO "DURAÇÃO EM MINUTOS"
FROM MODALIDADE
WHERE DURACAO = (SELECT MAX(DURACAO) FROM MODALIDADE);

--4- Retornar a competição que demora menos para terminar.
SELECT NOME "MODALIDADE QUE MENOS DEMORA", DURACAO "DURAÇÃO EM MINUTOS"
FROM MODALIDADE
WHERE DURACAO = (SELECT MIN(DURACAO) FROM MODALIDADE);

--5- Retornar as modalidades que mais premiam, especificando nome, categora e premiação.
SELECT NOME "MODALIDADES QUE MAIS PAGAM", CATEGORIA, PREMIACAO "PREMIAÇÃO"
FROM MODALIDADE
WHERE PREMIACAO = (SELECT MAX(PREMIACAO) FROM MODALIDADE)
ORDER BY 1 ASC;

--6- Retornar as modalidades que menos premiam, especificando nome, categora e premiação.
SELECT NOME "MODALIDADES QUE MENOS PAGAM", CATEGORIA, PREMIACAO "PREMIAÇÃO"
FROM MODALIDADE
WHERE PREMIACAO = (SELECT MIN(PREMIACAO) FROM MODALIDADE)
ORDER BY 1 ASC;

--7- Retornar as modalidades que iniciam com a letra B no nome.
SELECT * FROM MODALIDADE WHERE NOME LIKE 'B%';

--8- Retornar as modalidades que possuam a letra E em qualquer parte do nome.
SELECT * FROM MODALIDADE WHERE NOME LIKE '%E%';

--9- Retornar as modalidades que são realizadas em PISCINA.
SELECT LOCAL_DE_COMPETICAO, NOME, CATEGORIA FROM MODALIDADE 
WHERE LOCAL_DE_COMPETICAO IN ('PISCINA', 'ARENA')
--ORDER BY LOCAL_DE_COMPETICAO ASC
GROUP BY CATEGORIA, LOCAL_DE_COMPETICAO, NOME;

--10- Retornar as modalidades que tem a premiação entre 13.000,00 e 17.000,00.
SELECT * FROM MODALIDADE WHERE PREMIACAO BETWEEN 13000 AND 17000;

select * from modalidade where premiacao >= 13000 and premiacao <= 17000

select avg(premiacao) from modalidade

